"""Build two standalone, offline HTML files from editable sources. No dependencies."""
from pathlib import Path
import json
from html import escape as e
ROOT=Path(__file__).resolve().parent
SRC=ROOT/'src'
data=json.loads((SRC/'plan.json').read_text(encoding='utf-8'))
assert len({t['id'] for t in data['tasks']})==len(data['tasks'])
assert all(t['phase'] in {p['id'] for p in data['phases']} for t in data['tasks'])
css=(SRC/'style.css').read_text(encoding='utf-8')

def doc(title,body,script=''):
    return '<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="referrer" content="no-referrer"><title>'+e(title)+'</title><style>'+css+'</style></head><body>'+body+script+'</body></html>'

def prompt(t):
    return ('Я сам собираю новый Mosenc на WordPress и учусь по ходу. Помоги выполнить только '+t['id']+' — '+t['title']+'.\n'
     'Контекст: сначала русское локальное демо, каталог кофе и услуги, заявка/звонок, получение и оплата на заводе. Позже LV → EN → RU. Без онлайн-оплаты и доставки.\n'
     'Шаги:\n'+'\n'.join(str(n)+'. '+s for n,s in enumerate(t['steps'],1))+'\n'
     'Готово, когда: '+t['check']+'\n'
     'Сначала проверь фактическую среду и мой результат. Не запускай старые команды из архивов и не меняй другие проекты. Дай одно конкретное действие, короткое объяснение и проверку. Вопросы — по одному. Не выдавай весь курс. '
     'Код и техническую заготовку предлагай только если без них не обойтись; выполнение за меня — после моей отдельной просьбы. Перед рискованными изменениями нужна резервная точка. '
     'Не публикуй, не устанавливай платное, не отправляй письма и не меняй production без точного согласования. Не отмечай шаг выполненным вместо меня.')

def task_html(t):
    tid=e(t['id']); steps=''.join('<li>'+e(s)+'</li>' for s in t['steps'])
    links=''.join('<a href="#source-'+s+'">'+s+'</a>' for s in t['sources'])
    return f'''<article class="task" id="{tid}"><div class="check-wrap"><input type="checkbox" id="check-{tid}" aria-label="Сделал и проверил: {e(t['title'],quote=True)}"></div><details {'open' if tid=='M01' else ''}><summary><span><span class="task-id">{tid} · {'необязательно' if tid.startswith('X') else 'основной маршрут'}</span><strong>{e(t['title'])}</strong></span></summary><div class="task-body"><p class="time">Ориентир: {e(t['time'])}. Это объём работы, не обещание срока.</p><ol>{steps}</ol><div class="criterion"><b>Галочка — только после проверки</b>{e(t['check'])}</div><p class="learn"><b>Что освоишь:</b> {e(t['learn'])}</p><label class="note-label" for="note-{tid}">Мой результат / что мешает / где сохранено</label><textarea id="note-{tid}" maxlength="5000" placeholder="Например: проверил на телефоне; резервная копия в…; нужен разбор ошибки. Без паролей и данных клиентов."></textarea><details class="task-help"><summary>Нужна помощь? Готовый запрос наставнику / Antigravity</summary><p>Скопируй запрос вручную или кнопкой. При необходимости приложи скриншот и точный адрес локального сайта.</p><textarea readonly aria-label="Запрос по {tid}" id="prompt-{tid}">{e(prompt(t))}</textarea><button type="button" data-copy="prompt-{tid}">Скопировать запрос</button></details><div class="source-ref">Основано на: {links}</div></div></details></article>'''
nav=''.join(f'<a class="navlink" href="#phase-{p["id"]}"><span>{e(p["title"])}</span><small data-phase-count="{p["id"]}"></small></a>' for p in data['phases'])
sections=''
for n,p in enumerate(data['phases'],1):
    gate='<p class="gate">Стоп перед внешними действиями: эта часть выполняется после согласования с компанией. Готовность демо не даёт разрешения менять действующий сайт.</p>' if p['id']=='release' else ''
    gate+='<p class="gate">Эти улучшения не входят в основной процент. Выполняй только при реальной необходимости.</p>' if p['track']=='optional' else ''
    sections+=f'<section class="phase" id="phase-{p["id"]}"><header class="phase-head"><span class="phase-index">{n:02}</span><div><h2>{e(p["title"])}</h2><p>{e(p["result"])}</p></div></header>{gate}'+''.join(task_html(t) for t in data['tasks'] if t['phase']==p['id'])+'</section>'
sources=''
for s in data['sources']:
    title=f'<a href="{e(s["url"],quote=True)}" target="_blank" rel="noopener noreferrer">{e(s["title"])}</a>' if 'url' in s else e(s['title'])
    sources+=f'<article class="source" id="source-{s["id"]}"><h3>{s["id"]} · {title}</h3><p>{e(s["use"])}</p>'+('<code>От Desktop: '+e(s['where'])+'</code>' if 'where' in s else '')+'</article>'
body=f'''<a class="skip" href="#main">К плану</a><div class="layout"><aside class="sidebar"><div class="brand">MOSENC<small>РАБОЧАЯ ТЕТРАДЬ · GADEMRAYT</small></div><nav aria-label="Этапы">{nav}<a class="navlink" href="#sources">Источники и решения</a></nav><p class="side-note">Ты собираешь сайт.<br>Hermes ведёт по шагам.<br>Antigravity помогает точечно.<br><br>Без повторного курса.<br>Без гонки за всеми галочками.</p></aside><main id="main"><header class="hero"><p class="kicker">Новый маршрут · {e(data['revision'])}</p><h1>Свой сайт.<br>По одному шагу.</h1><p>Собрать Mosenc на WordPress своими руками: сначала понятное русское демо, затем согласованный запуск и портфолио. Обучение — внутри работы, а не перед ней.</p><div class="journey"><span>Выбрать кофе</span><b>→</b><span>Позвонить / оставить заявку</span><b>→</b><span>Подтвердить с сотрудником</span><b>→</b><span>Оплатить и забрать на заводе</span></div></header>
<noscript><p class="noscript">JavaScript выключен. Инструкции доступны, но отметки, экспорт и сохранение не работают. Включи JavaScript для рабочего блокнота.</p></noscript>
<section class="panel" aria-label="Прогресс"><div class="progress-top"><div><b>Основной маршрут</b><div class="muted" id="demo-count"></div></div><div class="progress-number" id="percent">0%</div></div><progress id="progress" value="0" max="30" aria-label="Выполненные шаги"></progress><div class="progress-top"><span id="count">0 / 30</span><span class="muted">Твои отметки, не автоматическая сертификация сайта</span></div><div class="toolbar"><a class="button primary" href="index.html">← Перейти на сайт Mosenc</a><button class="primary" id="export">Экспорт отметок</button><button id="import">Загрузить отметки</button><input id="import-file" type="file" accept=".json,application/json" hidden><button id="print">Печать / PDF</button><a class="button" href="overview.html" target="_blank" rel="noopener">Обзор для шефа ↗</a><button id="reset" class="danger">Сбросить</button><button id="raw-backup" hidden>Скачать повреждённую копию</button></div><p class="small muted">Галочки и заметки живут в этом браузере. Экспортируй в конце работы и перед переносом папки. Они не записываются в HTML, Git или GitHub автоматически. На другом устройстве или адресе загрузи экспорт.</p><div class="notice" id="status" role="status" aria-live="polite">План открыт. Старые проекты и отметки Mastery не изменены.</div></section>
<section class="panel next"><p><span class="kicker">Сейчас достаточно одного шага</span><strong id="next-title">M01 · Выбрать чистую локальную площадку</strong></p><button class="primary" id="next-button">Перейти к шагу ↓</button></section>
<details class="rules"><summary>Как работать с планом — коротко</summary><div class="body"><div class="scope-grid"><div class="panel"><h3>Новый старт, не уничтожение старого</h3><p>Этот маршрут начинается с нуля. Старые проекты, исходники и принятые учебные задания остаются отдельно. Не импортируем весь старый сайт и не заставляем заново проходить общий курс.</p><p>Новая WordPress-среда ещё не создана. Тема, плагины, фактический адрес и хостинг проверяются на соответствующем шаге.</p></div><div class="panel"><h3>Одна сессия — видимый результат</h3><p>Открой первый незавершённый шаг → сделай → проверь по критерию → оставь заметку → поставь галочку → экспортируй отметки. Если не получается — запиши конкретный блокер и попроси одно следующее действие.</p><p>План — основной журнал этого нового проекта. Mastery остаётся справочником, без автоматической синхронизации статусов.</p></div></div><ul><li><b>Сейчас:</b> русский сайт, каталог, услуги, телефон и заявка, оплата/получение на заводе.</li><li><b>Позже:</b> основной LV, затем EN, затем RU; всё содержание и сообщения без смеси языков.</li><li><b>Не сейчас:</b> онлайн-оплата, доставка, аккаунты, фильтры ради красоты, обязательный PHP-курс, конвейер из всех AI.</li><li><b>Моя рекомендация:</b> одна ручная сборка Kadence + Gutenberg/Kadence Blocks; сначала проверить совместимость. Не обязательно переносить HTML в кастомную тему.</li><li><b>Первый показ:</b> законченная главная → связное русское демо → отдельное согласование компании. Красивый макет не подтверждает работу формы.</li><li><b>Сохранение:</b> код/план — Git при настройке; БД/медиа — отдельные копии; личные отметки — экспорт JSON. Vercel только по желанию и после проверки приватности.</li></ul><p class="muted">Гарантировать продажи или решение шефа невозможно. Этот план задаёт проверяемый путь к рабочему сайту и понятному собственному вкладу.</p></div></details>
<div class="filterbar"><label for="filter">Показать</label><select id="filter"><option value="all">Все шаги</option><option value="open">Только незавершённые</option><option value="done">Только выполненные</option></select><button id="expand">Раскрыть инструкции</button><button id="collapse">Свернуть инструкции</button></div><p id="empty" class="empty" hidden>В этом фильтре пока нет шагов.</p>{sections}<section class="sources" id="sources"><h2>Источники — не ещё одна очередь заданий</h2><p>Проверены ключевые материалы, а не каждый файл во всех папках. Приоритет: твои новые решения → актуальные факты и проверки → старые материалы как справочник. Архивные команды не запускаем автоматически.</p><p><b>Что отсечено:</b> старые интернет-платежи и доставка, переход в Django, обязательная кастомная тема, автоматическая публикация Vercel, большие учебные блоки перед первым результатом. Полезные правила: структура до верстки, один визуальный ориентир, настоящее получение заявок, проверка после каждого этапа.</p>{sources}</section><footer class="footer">Создан Hermes по материалам Витальки. Это план, не результат сборки WordPress. Реальный сайт, GitHub и Vercel этим файлом не изменяются. Для показа без рабочих заметок используй отдельный overview.html; перед внешней передачей согласуй раскрытие проекта.</footer></main></div>'''
script='<script id="plan-data" type="application/json">'+json.dumps(data,ensure_ascii=False).replace('<','\\u003c')+'</script><script>'+(SRC/'state.js').read_text(encoding='utf-8')+'</script><script>'+(SRC/'app.js').read_text(encoding='utf-8')+'</script>'
(ROOT/'plan.html').write_text(doc(data['title'],body,script),encoding='utf-8')
overview='''<main class="overview"><p class="kicker">Mosenc · предложение по обновлению сайта</p><h1>Выбрать кофе онлайн.<br>Забрать на заводе.</h1><p>План первой версии на WordPress: показать ассортимент и услуги, упростить обращение и сохранить возможность дальнейшего развития.</p><div class="signature"><b>Путь клиента</b><p>Кофе → карточка → звонок или заявка → подтверждение сотрудником → получение и оплата на заводе.</p></div><div class="scope-grid"><section class="panel"><h2>В первой версии</h2><ul><li>Каталог кофе с понятными карточками.</li><li>Информация о компании, услугах и контактах.</li><li>Запрос кофе и обращение по услугам.</li><li>Удобное отображение на телефоне.</li><li>Редактирование содержания через WordPress.</li></ul></section><section class="panel"><h2>Отдельно, позже</h2><ul><li>Онлайн-оплата и доставка.</li><li>Личные кабинеты и программа лояльности.</li><li>Расширение каталога и автоматизации.</li></ul><p>Эти функции не являются условием первой версии.</p></section></div><h2>Порядок работы</h2><ol><li><b>Русское локальное демо.</b> Главная, каталог, услуги и безопасная демонстрация заявки.</li><li><b>Обсуждение с компанией.</b> Утверждение структуры, содержания, объёма и расходов.</li><li><b>Подготовка выпуска.</b> Подтверждённые материалы, LV / EN / RU с латышским основным, тестовая площадка, проверка форм и переноса.</li><li><b>Запуск и передача.</b> Только после разрешения: резервная копия, проверки, инструкция ответственному.</li></ol><h2>Что потребуется от компании</h2><p>Подтвердить ассортимент, фотографии, характеристики, условия получения и оплаты на месте; назначить получателя заявок и проверяющего переводы; согласовать размещение и обслуживание сайта.</p><div class="panel"><b>Текущий статус</b><p>Подготовлен план. Этот документ не утверждает, что сайт уже собран, согласован или опубликован. Срок и бюджет определяются после уточнения объёма и первых практических результатов.</p></div><p>Работу выполняет Виталька с использованием ИИ как помощника. Публикация кейса в портфолио — по отдельному разрешению компании.</p><button class="no-print" onclick="window.print()">Печать / сохранить PDF</button></main>'''
(ROOT/'overview.html').write_text(doc('Mosenc — предложение по обновлению сайта',overview),encoding='utf-8')
print(json.dumps({'tasks':len(data['tasks']),'required':sum(not t['id'].startswith('X') for t in data['tasks']),'sources':len(data['sources']),'files':['plan.html','overview.html']},ensure_ascii=False))
